#pragma once

using namespace ATL;

template <class T>
class CProxy_ITATLControlEvents : public IConnectionPointImpl<T, &__uuidof(_ITATLControlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
